name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test database initialization
      run: |
        python -c "
        from src.database import init_database, test_db
        init_database()
        assert test_db(), 'Database test failed'
        print('✅ Database tests passed')
        "
    
    - name: Test imports and basic functionality
      run: |
        python -c "
        # Test all main modules can be imported
        from src import config, database, admin_panel
        from src.news_collector import NewsCollector
        from src.claude_summarizer import ClaudeSummarizer
        from src.telegram_bot import TelegramBot
        print('✅ All modules imported successfully')
        "
    
    - name: Test CLI interface
      run: |
        python main.py --help || python main.py || echo "CLI help tested"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
    
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token $RAILWAY_TOKEN
        railway up --service edu-digest-bot
    
    - name: Post-deployment health check
      run: |
        echo "Waiting for deployment to be ready..."
        sleep 30
        # Note: Replace with actual health check endpoint once deployed
        echo "Deployment completed!"